using Finance.Application.UseCases;
using Finance.Application.UseCases.Accounts.CreateAccount;
using Finance.Application.UseCases.Accounts.CreateAccount.Request;
using Finance.Application.UseCases.Accounts.CreateAccount.Response;
using Finance.Application.UseCases.Accounts.DeleteAccount;
using Finance.Application.UseCases.Accounts.DeleteAccount.Request;
using Finance.Application.UseCases.Accounts.DeleteAccount.Response;
using Finance.Application.UseCases.Accounts.GetAccountById;
using Finance.Application.UseCases.Accounts.GetAccountById.Request;
using Finance.Application.UseCases.Accounts.GetAccountById.Response;
using Finance.Application.UseCases.Accounts.GetAccountsByUserId;
using Finance.Application.UseCases.Accounts.GetAccountsByUserId.Request;
using Finance.Application.UseCases.Accounts.GetAccountsByUserId.Response;
using Finance.Application.UseCases.Accounts.GetValueAccounts;
using Finance.Application.UseCases.Accounts.GetValueAccounts.Request;
using Finance.Application.UseCases.Accounts.GetValueAccounts.Response;
using Finance.Application.UseCases.Accounts.UpdateAccount;
using Finance.Application.UseCases.Accounts.UpdateAccount.Request;
using Finance.Application.UseCases.Accounts.UpdateAccount.Response;
using Finance.Application.UseCases.Budgets.DeleteBudget;
using Finance.Application.UseCases.Budgets.DeleteBudget.Request;
using Finance.Application.UseCases.Budgets.DeleteBudget.Response;
using Finance.Application.UseCases.Budgets.GetBudgetById;
using Finance.Application.UseCases.Budgets.GetBudgetById.Request;
using Finance.Application.UseCases.Budgets.GetBudgetById.Response;
using Finance.Application.UseCases.Budgets.GetBudgetsByUserId;
using Finance.Application.UseCases.Budgets.GetBudgetsByUserId.Request;
using Finance.Application.UseCases.Budgets.GetBudgetsByUserId.Response;
using Finance.Application.UseCases.Budgets.GetBudgetsStatus;
using Finance.Application.UseCases.Budgets.GetBudgetsStatus.Request;
using Finance.Application.UseCases.Budgets.GetBudgetsStatus.Response;
using Finance.Application.UseCases.Budgets.GetBudgetsSummary;
using Finance.Application.UseCases.Budgets.GetBudgetsSummary.Request;
using Finance.Application.UseCases.Budgets.GetBudgetsSummary.Response;
using Finance.Application.UseCases.Budgets.UpdateBudget;
using Finance.Application.UseCases.Budgets.UpdateBudget.Request;
using Finance.Application.UseCases.Budgets.UpdateBudget.Response;
using Finance.Application.UseCases.Budgets.СreateBudget;
using Finance.Application.UseCases.Budgets.СreateBudget.Request;
using Finance.Application.UseCases.Budgets.СreateBudget.Response;
using Finance.Application.UseCases.Categories.GetCategories;
using Finance.Application.UseCases.Categories.GetCategories.Request;
using Finance.Application.UseCases.Categories.GetCategories.Response;
using Finance.Application.UseCases.Transactions.CreateTransaction;
using Finance.Application.UseCases.Transactions.CreateTransaction.Request;
using Finance.Application.UseCases.Transactions.CreateTransaction.Response;
using Finance.Application.UseCases.Transactions.DeleteTransaction;
using Finance.Application.UseCases.Transactions.DeleteTransaction.Request;
using Finance.Application.UseCases.Transactions.DeleteTransaction.Response;
using Finance.Application.UseCases.Transactions.GetTransactionById;
using Finance.Application.UseCases.Transactions.GetTransactionById.Request;
using Finance.Application.UseCases.Transactions.GetTransactionById.Response;
using Finance.Application.UseCases.Transactions.GetTransactions;
using Finance.Application.UseCases.Transactions.GetTransactions.Request;
using Finance.Application.UseCases.Transactions.GetTransactions.Response;
using Finance.Application.UseCases.Transactions.GetTransactionsByAccountId;
using Finance.Application.UseCases.Transactions.GetTransactionsByAccountId.Request;
using Finance.Application.UseCases.Transactions.GetTransactionsByAccountId.Response;
using Finance.Application.UseCases.Transactions.GetTransactionsSummary;
using Finance.Application.UseCases.Transactions.GetTransactionsSummary.Request;
using Finance.Application.UseCases.Transactions.GetTransactionsSummary.Response;
using Finance.Application.UseCases.Transactions.UpdateTransaction;
using Finance.Application.UseCases.Transactions.UpdateTransaction.Request;
using Finance.Application.UseCases.Transactions.UpdateTransaction.Response;
using Finance.Application.Validators;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;
using SharpGrip.FluentValidation.AutoValidation.Mvc.Extensions;
namespace Finance.Application.DependencyInjection
{
    public static class DependencyInjection
    {
        public static IServiceCollection AddApplication(this IServiceCollection services)
        {
            services.AddScoped<IUseCase<CreateAccountRequest,CreateAccountResponse>,CreateAccountUseCase>();
            services.AddScoped<IUseCase<GetAccountByIdRequest, GetAccountByIdResponse>, GetAccountByIdUseCase>();
            services.AddScoped<IUseCase<GetValueAccountsRequest, GetValueAccountsResponse>, GetValueAccountsUseCase>();
            services.AddScoped<IUseCase<GetAccountsByUserIdRequest, GetAccountsByUserIdResponse>, GetAccountsByUserIdUseCase>();
            services.AddScoped<IUseCase<DeleteAccountRequest, DeleteAccountResponse>, DeleteAccountUseCase>();
            services.AddScoped<IUseCase<UpdateAccountRequest, UpdateAccountResponse>, UpdateAccountUseCase>();
            services.AddScoped<IUseCase<CreateBudgetRequest, CreateBudgetResponse>, CreateBudgetUseCase>();
            services.AddScoped<IUseCase<DeleteBudgetRequest, DeleteBudgetResponse>, DeleteBudgetUseCase>();
            services.AddScoped<IUseCase<GetBudgetByIdRequest, GetBudgetByIdResponse>, GetBudgetByIdUseCase>();
            services.AddScoped<IUseCase<GetBudgetsByUserIdRequest, GetBudgetsByUserIdResponse>, GetBudgetsByUserIdUseCase>();
            services.AddScoped<IUseCase<GetBudgetsSummaryRequest, GetBudgetsSummaryResponse>, GetBudgetsSummaryUseCase>();
            services.AddScoped<IUseCase<GetBudgetsStatusRequest, GetBudgetsStatusResponse>, GetBudgetsStatusUseCase>();
            services.AddScoped<IUseCase<UpdateBudgetRequest, UpdateBudgetResponse>, UpdateBudgetUseCase>();
            services.AddScoped<IUseCase<GetCategoriesRequest, GetCategoriesResponse>, GetCategoriesUseCase>();
            services.AddScoped<IUseCase<CreateTransactionRequest, CreateTransactionResponse>, CreateTransactionUseCase>();
            services.AddScoped<IUseCase<DeleteTransactionRequest, DeleteTransactionResponse>, DeleteTransactionUseCase>();
            services.AddScoped<IUseCase<UpdateTransactionRequest, UpdateTransactionResponse>, UpdateTransactionUseCase>();
            services.AddScoped<IUseCase<GetTransactionsByAccountIdRequest, GetTransactionsByAccountIdResponse>, GetTransactionsByAccountIdUseCase>();
            services.AddScoped<IUseCase<GetTransactionByIdRequest, GetTransactionByIdResponse>, GetTransactionByIdUseCase>();
            services.AddScoped<IUseCase<GetTransactionsRequest, GetTransactionsResponse>, GetTransactionsUseCase>();
            services.AddScoped<IUseCase<GetTransactionsSummaryRequest, GetTransactionSummaryResponse>, GetTransactionsSummaryUseCase>();
            services.AddValidatorsFromAssemblyContaining<CreateAccountRequestValidator>();
            services.AddFluentValidationAutoValidation();
            return services;
        }
    }
}
