version: '3.8'

services:
  redis:
    image: redis
    container_name: budget-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data  
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 10s
    restart: unless-stopped
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"      
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_/var/lib/rabbitmq
    networks:
      - app
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: budget-mailhog
    ports:
      - "1025:1025"   
      - "8025:8025"  
    networks:
      - app
    restart: unless-stopped

  auth-api:
    build:
      context: ./AuthService
      dockerfile: Auth.API/Dockerfile
    ports:  
      - "8081:8080" 
    expose:
      - "8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Redis=redis:6379,abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    networks:
      - app

  budgetserver:
    build:
      context: ./FinanceService
      dockerfile: BudgetServer/Dockerfile
    ports:
      - "5000:5000" 
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Redis=redis:6379,abortConnect=false,connectTimeout=5000,syncTimeout=5000
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    networks:
      - app

  notificationservice:
    build:
      context: ./NotificationService
      dockerfile: NotificationService.API/Dockerfile
    container_name: budget-notifications
    ports:
      - "5002:5002"
    expose:
      - "5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      # Добавить дб для docker
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      # Email Settings (MailHog для разработки)
      - EmailSettings__SmtpServer=mailhog
      - EmailSettings__SmtpPort=1025
      - EmailSettings__SmtpUser=
      - EmailSettings__SmtpPassword=
      - EmailSettings__SmtpUseSsl=false
      - EmailSettings__FromEmail=
      - EmailSettings__FromName=Budget App
      - Jwt__Issuer=BudgetApp
      - Jwt__Audience=BudgetApp
      - Jwt__Secret=your-super-secret-key-min-32-chars!!
    depends_on:
      postgres-notifications:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      mailhog:
        condition: service_started
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # ← nginx слушает 8080 на хосте
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-api
      - budgetserver
      - notificationservice
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  redis:
  rabbitmq: 