# nginx.conf
events {
    worker_connections 1024;
}

http {
    upstream auth_api {
        server auth-api:8080;
    }

    upstream budget_api {
        server budgetserver:5000;
    }

    server {
        listen 80;
        server_name localhost;

        # Проксируем API
        location /api/auth/ {
            proxy_pass http://auth_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
        }

        location /api/budget/ {
            proxy_pass http://budget_api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
        }

        # не обрабатываем (фронтенд на 5173)
        location / {
            return 404;
        }
    }
}